### ISSUE TITLE
name 'EXPORT_SAVE_PATH' is not defined

### ISSUE THREAD

**Issue by TERESH1** [joelmaxw311/BarotraumaSaveEditor#1]
```
Traceback (most recent call last):
  File "save_editor.py", line 169, in <module>
    retcode = main(sys.argv)
  File "save_editor.py", line 147, in main
    export_save(save_file) # export to a .save
  File "save_editor.py", line 118, in export_save
    path_out = EXPORT_SAVE_PATH # path of temporary .save file to create
NameError: name 'EXPORT_SAVE_PATH' is not defined
```

**Comment by TERESH1** [comment]
#2
